#!/usr/bin/env Rscript

# One-command package workflow:
# 1) roxygen2::roxygenise()
# 2) testthat::test_local()
# 3) R CMD build
# 4) R CMD check

args <- commandArgs(trailingOnly = TRUE)

usage <- function() {
  cat(
    paste(
      "Usage: Rscript scripts/check-package.R [options]",
      "",
      "Options:",
      "  --as-cran         Run R CMD check with --as-cran (default: TRUE)",
      "  --no-as-cran      Disable --as-cran",
      "  --no-manual       Run R CMD check with --no-manual",
      "  --skip-document   Skip roxygen2::roxygenise()",
      "  --skip-tests      Skip testthat::test_local()",
      "  --skip-check      Skip R CMD check",
      "  --no-clean        Keep previous *.Rcheck and tar.gz artifacts",
      "  --help            Show this help message",
      sep = "\n"
    )
  )
}

if ("--help" %in% args) {
  usage()
  quit(save = "no", status = 0)
}

opts <- list(
  as_cran = !("--no-as-cran" %in% args),
  no_manual = ("--no-manual" %in% args),
  skip_document = ("--skip-document" %in% args),
  skip_tests = ("--skip-tests" %in% args),
  skip_check = ("--skip-check" %in% args),
  clean = !("--no-clean" %in% args)
)

if ("--as-cran" %in% args) {
  opts$as_cran <- TRUE
}

arg_file <- grep("^--file=", commandArgs(), value = TRUE)
if (length(arg_file) == 0) {
  stop("Could not resolve script path from --file=...", call. = FALSE)
}
script_path <- normalizePath(sub("^--file=", "", arg_file[[1]]), winslash = "/", mustWork = TRUE)
repo_root <- normalizePath(file.path(dirname(script_path), ".."), winslash = "/", mustWork = TRUE)
setwd(repo_root)

message("Repository root: ", repo_root)

ensure_pkg <- function(pkg) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    user_lib <- path.expand(Sys.getenv("R_LIBS_USER"))
    if (!nzchar(user_lib)) {
      user_lib <- path.expand("~/R/win-library/4.5")
    }
    dir.create(user_lib, recursive = TRUE, showWarnings = FALSE)
    .libPaths(c(user_lib, .libPaths()))
    repos <- getOption("repos")
    if (is.null(repos) || identical(repos[["CRAN"]], "@CRAN@")) {
      repos <- c(CRAN = "https://cloud.r-project.org")
      options(repos = repos)
    }
    message("Installing missing package '", pkg, "' into ", user_lib)
    install.packages(pkg, lib = user_lib, repos = repos[["CRAN"]])
    if (!requireNamespace(pkg, quietly = TRUE)) {
      stop("Failed to install required package '", pkg, "'.", call. = FALSE)
    }
  }
}

run_cmd <- function(command, arguments) {
  message(">> ", command, " ", paste(arguments, collapse = " "))
  status <- system2(command, args = arguments)
  if (!identical(status, 0L)) {
    stop("Command failed: ", command, " ", paste(arguments, collapse = " "), call. = FALSE)
  }
}

if (opts$clean) {
  old_artifacts <- unique(c(
    Sys.glob("*.Rcheck"),
    Sys.glob("..Rcheck"),
    Sys.glob("*_*.tar.gz"),
    "tests/testthat/Rplots.pdf"
  ))
  old_artifacts <- old_artifacts[file.exists(old_artifacts)]
  if (length(old_artifacts) > 0) {
    message("Cleaning previous artifacts...")
    unlink(old_artifacts, recursive = TRUE, force = TRUE)
  }
}

if (!opts$skip_document) {
  ensure_pkg("roxygen2")
  message("==> Documenting package")
  roxygen2::roxygenise(package.dir = repo_root)
}

if (!opts$skip_tests) {
  ensure_pkg("testthat")
  message("==> Running testthat")
  testthat::test_local(path = repo_root, reporter = "summary", stop_on_failure = TRUE)
}

r_exe <- Sys.which("R")
if (!nzchar(r_exe)) {
  candidate <- file.path(R.home("bin"), "R.exe")
  if (file.exists(candidate)) {
    r_exe <- candidate
  }
}
if (!nzchar(r_exe) || !file.exists(r_exe)) {
  stop("Could not find R executable for running CMD build/check.", call. = FALSE)
}

message("==> Building source tarball")
run_cmd(r_exe, c("CMD", "build", "."))

tarballs <- sort(Sys.glob("*_*.tar.gz"), decreasing = TRUE)
if (length(tarballs) == 0) {
  stop("No source tarball generated by R CMD build.", call. = FALSE)
}
tarball <- tarballs[[1]]
message("Built tarball: ", tarball)

if (!opts$skip_check) {
  check_args <- c("CMD", "check")
  if (opts$as_cran) {
    check_args <- c(check_args, "--as-cran")
  }
  if (opts$no_manual) {
    check_args <- c(check_args, "--no-manual")
  } else if (!nzchar(Sys.which("pdflatex"))) {
    message("pdflatex not found; using --no-manual automatically.")
    check_args <- c(check_args, "--no-manual")
  }
  check_args <- c(check_args, tarball)
  message("==> Running R CMD check")
  run_cmd(r_exe, check_args)
}

message("Package check workflow completed successfully.")
